sudo: required
services:
    - docker

before_install:
    - docker build -t gropa-dev/react-test -f ./client/dockerfile.dev ./client

script:
    - docker run gropa-dev/react-test npm test -- --coverage

after_success:
    - docker build -t gropa-dev/multi-client ./client
    - docker build -t gropa-dev/multi-nginx ./nginx
    - docker build -t gropa-dev/multi-server ./server
    - docker build -t gropa-dev/multi-worker ./worker
    # log in to the docker CLI
    -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push gropa-dev/multi-client
    - docker push gropa-dev/multi-nginx
    - docker push gropa-dev/multi-server
    - docker push gropa-dev/multi-worker